use_frameworks!

platform :ios, '8.0'

target 'SPPodTest_Example' do
  pod 'SPPodTest', :path => '../'

  target 'SPPodTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
